# Site settings
title: Amit Zur | Ninja
email: zur.amit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://amitzur.ninja"
twitter_username: amitzur
github_username:  amitzur

# Build settings
markdown: kramdown
#sass:
#  style: :compressed