# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Amit Zur
tagline:          'A personal blog'
description:      'Pixels, bits and mindfulness'
url:              http://amitzur.ninja
baseurl:          /

author:
  name:           'Amit Zur'
  url:            https://amitzur.ninja

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/amitzur/amitzur.ninja

#sass:
#  style: :compressed